// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0SHFiTodL-R9u0yrpvg8s3GxHeqPi6Hc',
    appId: '1:1052564625492:web:4e3d26fc789f3654b135c1',
    messagingSenderId: '1052564625492',
    projectId: 'webrtc-7e516',
    authDomain: 'webrtc-7e516.firebaseapp.com',
    storageBucket: 'webrtc-7e516.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2aWy2eUwwoapWt8GOBfMsGqaHrM8B1Xg',
    appId: '1:1052564625492:android:ab41fea25f608839b135c1',
    messagingSenderId: '1052564625492',
    projectId: 'webrtc-7e516',
    storageBucket: 'webrtc-7e516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRz1nb72FXcPoK5mK2omro4aIrhTx17Us',
    appId: '1:1052564625492:ios:47110d77f217dedab135c1',
    messagingSenderId: '1052564625492',
    projectId: 'webrtc-7e516',
    storageBucket: 'webrtc-7e516.appspot.com',
    iosBundleId: 'com.example.flutterMeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRz1nb72FXcPoK5mK2omro4aIrhTx17Us',
    appId: '1:1052564625492:ios:e19fb0bf131687b1b135c1',
    messagingSenderId: '1052564625492',
    projectId: 'webrtc-7e516',
    storageBucket: 'webrtc-7e516.appspot.com',
    iosBundleId: 'com.example.flutterMeet.RunnerTests',
  );
}
